import React from "react"
import ReactMarkdown from "react-markdown";
import Layout from "../components/layout";
import Map from "../components/elements/map";
import {Container, Row, Col} from "react-bootstrap";
import Seo from "../components/structure/SEO";
const contStyles = {
    color: "purple",
}
const Object = props => {
    const {
        pageContext: {...object},
    } = props
    const isSSR = typeof window === "undefined";

    return (
        <>
            <Layout>
                <Seo title={'An object record for ' + object.objectID}/>
                <Container className="mb-2 post-body">
                    <h1 className="fw-bolder" style={contStyles}>
                        {object.objectID.toUpperCase() + ': '} {object.objectType}
                    </h1>
                    {object.collection && <p><strong>Provenance notes:</strong> {object.collection}</p>}
                    {object.museumCollection && <p><strong>Holding museum:</strong> {object.museumCollection}</p>}

                    <h2 className={"object-heading"}>Dating</h2>

                    <p>{object.broadperiod} {object.fromdate && Math.abs(object.fromdate) + 'BC'} {object.todate && ' - ' + Math.abs(object.todate) + 'BC'}</p>
                    {object.PASID && <p><a href={`https://finds.org.uk/database/objects/id/${object.PASID}`}>View this on the Portable Antiquities Scheme Database</a></p>}
                    {object.project && <>
                        <p><a href={`https://crowdsourced.micropasts.org/project/${object.project}`}>Micropasts Project</a></p>
                        <p>This record was generated by the MicroPasts community in 2014, during the major citizen science project that
                        catalogued these index cards. There maybe errors below.</p>
                    </>}
                    {object.imageURL !== 'undefined' && <Row className={"my-2"}><Col md={12}><img src={object.imageURL} alt={object.objectType} className={"img-fluid"}/></Col></Row>}

                    {object.description && <ReactMarkdown>{object.description}</ReactMarkdown>}
                    {object.notes && <ReactMarkdown>{object.notes}</ReactMarkdown>}
                    {object.remarks && <ReactMarkdown>{object.remarks}</ReactMarkdown>}
                    {object.composition && <><h3>Composition</h3><ReactMarkdown>{object.composition}</ReactMarkdown></>}
                    {object.surface && <><h3>Surface</h3><ReactMarkdown>{object.surface}</ReactMarkdown></>}
                    {object.associations && <><h3>Associations</h3>
                        <ReactMarkdown>{object.associations}</ReactMarkdown></>}
                    {object.publications && <><h3>Publications</h3>
                        <ReactMarkdown>{object.publications}</ReactMarkdown></>}
                    <h3>Location</h3>
                    <ul>
                        {object.country && <li>{object.country}</li>}
                        {object.regionName && <li>{object.regionName}</li>}
                        {object.county && <li>{object.county}</li>}
                        {object.district && <li>{object.district}</li>}
                        {object.parish && <li>{object.parish}</li>}
                        {object.knownas && <li>{object.knownas}</li>}
                    </ul>
                    {object.site && <p>BAI index card site: {object.site}</p>}
                    {object.gridRef && <p>Grid Reference: {object.gridRef}</p>}
                    {object.toSearch && <p>MicroPasts: {object.toSearch}</p>}
                </Container>

                {!isSSR && object.fourFigureLat && (
                    <Map geo_lat={object.fourFigureLat} geo_lon={object.fourFigureLon}/>
                )}
                <Container fluid className="py-3 bg-pale">
                    <Container>
                        {object.datefound1 &&  <><h3>Discovery</h3>
                        <p>
                            {object.discoveryMethod}<br/>
                            {object.datefound1 && <span>{object.datefound1}</span>} {object.datefound2 &&
                            <span> - {object.datefound1}</span>}
                        </p></>}
                        {object.subsequentActionTerm && <><h3>What happened to it?</h3>
                        <p>{object.subsequentActionTerm}</p></>}

                        {object.identifier && <><h3>Who identified it?</h3><p>{object.identifier}</p></>}
                        {object.inputBy && <p>Entered by MicroPasts Contributor: {object.inputBy}</p>}
                        <ul>
                            {object.materialTerm && <li>Made from: {object.materialTerm}</li>}
                            {object.quantity && <li>Quantity: {object.quantity}</li>}
                            {object.edge && <li>Edge: {object.edge}</li>}
                            {object.length && <li>Length: {object.length}</li>}
                            {object.thickness && <li>Thickness: {object.thickness}</li>}
                            {object.diameter && <li>Diameter: {object.diameter}</li>}
                        </ul>
                    </Container>
                </Container>

            </Layout>
        </>
    )
}


export default Object