import React from "react";
import PropTypes from "prop-types";
import {Alert} from "react-bootstrap";
const MicropastsProject = ({object}) => (
    <>
        {object.project && <>

            <Alert variant="dark">
                <Alert.Heading>Crowd-powered data</Alert.Heading>
                This record was generated by the MicroPasts community in 2014, during the major citizen science project that
                catalogued these index cards. There maybe errors below.
            </Alert>
            <a className={"btn btn-dark my-2"} href={`https://crowdsourced.micropasts.org/project/${object.project}`}>This was part of a Micropasts Project</a>
        </>}
    </>
);

MicropastsProject.propTypes = {
    object: PropTypes.array.isRequired,
}

MicropastsProject.defaultProps = {
    object: [],
}

export default MicropastsProject;