import React from "react";
import {Container, Col, Row} from "react-bootstrap";

const styles = {
    paddingLeft: '0',
    paddingRight: '0',
}
const Mold = () => (
    <Container fluid className={'bg-dark py-4'} style={styles}>
        <Row>
            <Col md={6} className="d-flex align-items-center justify-content-center text-white p-2 my-2">
                <Col md={8} className="mx-auto align-middle">
                    <h1 className={"text-white text-center fw-bolder"}>
                        3D Models
                    </h1>
                    <p>
                        The MicroPasts team ran a citizen science powered 3D modelling series of projects during the <a href={"https://ahrc.ukri.org"} className={"text-white"}>Arts and Humanities Research Council</a> funded phase. Over 100 models were generated by the public, and these are now available to view
                        and  download from Sketchfab and are integrated here.
                    </p>
                    <p>
                        These objects range from broken and complete palstave axes, hoard such as Goudhurst, Stibbard and Arreton Down to large ceremonial dirks and swords.
                    </p>
                    <p>
                        Please feel free to download and remix these models, and if you do, please let us know!
                    </p>
                    <p className={"text-center"}><a href="https://sketchfab.com/micropasts" className="btn btn-dark rounded-0 border-white text-white">Discover
                        our models</a></p>
                </Col>
            </Col>

            <Col md={6} className={"text-center  my-2 px-3 mr-3"}>
                <div className={"ratio ratio-16x9 rounded-4"}>
                    <iframe className={"rounded-4"} title="The Oxborough Dirk" allowFullScreen mozallowfullscreen="true"
                            webkitallowfullscreen="true" allow="autoplay; fullscreen;"
                            src="https://sketchfab.com/models/b406491728b642c88b5e7bd4b3b68f2f/embed"></iframe>
                </div>
            </Col>

        </Row>
    </Container>
)

export default Mold
